server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Superbus45!
  jpa:
    open-in-view: false

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packagesToScan: com.clintonbeardsley.ileostomytracker.controller
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha